name = "OFIM"
author = "goma"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb28c64e8ee89d037c479a3e2f07a5ae3887b004b9cbc2e182f2cafb7eecc47b"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.88"
