name = "OFIM"
author = "goma"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cb01f0d1fb9715289c70a5fa7b78e260b0697aaec8e27fb46b7c5840983fc4f"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.88"
