name = "OFIM"
author = "goma"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0288b0532c68f387b76a9e0dfc06501137e0a3ef9fa8c2f6abbf032327631120"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.88"
